# Spectral configuration for OpenAPI/AsyncAPI linting
# Enforces API design standards and consistency

extends: [[spectral:oas, all], [spectral:asyncapi, all]]

rules:
  # Require operation IDs for all endpoints
  operation-operationId: error

  # Require descriptions
  operation-description: warn
  operation-summary: error
  info-description: error

  # Require examples
  operation-examples: warn

  # Security requirements
  operation-security-defined: error

  # Tag usage
  operation-tags: error
  operation-tag-defined: error

  # Request/Response requirements
  operation-success-response: error
  oas3-api-servers: error

  # Contact information
  info-contact: warn
  contact-properties: warn

  # License information
  info-license: error
  license-url: error

  # Versioning
  oas3-valid-media-example: error
  oas3-valid-schema-example: error

  # Custom rules
  no-$ref-siblings: error
  typed-enum: warn

  # Naming conventions
  paths-kebab-case: error

# Custom rules for your API standards
functionsDir: .github/spectral-functions
